-- Let's create a table called users which will just store their phone number along with an autogenerated ID
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL
);

SELECT * from users